import { Property, Area } from '@/types/property';

// Mock properties for development until XML integration
export const MOCK_PROPERTIES: Property[] = [
    {
        id: '1',
        ref: 'SP0892',
        slug: 'villa-marbella-golden-mile',
        price: 1250000,
        currency: 'EUR',
        type: 'Villa',
        title: 'Villa Vista Mare',
        isNewBuild: false,
        town: 'Marbella',
        province: 'Málaga',
        country: 'Spain',
        locationDetail: 'Golden Mile',
        coordinates: { lat: 36.5097, lng: -4.8857 },
        region: 'costa-del-sol',
        beds: 4,
        baths: 3,
        builtArea: 280,
        plotArea: 1050,
        terraceArea: 120,
        energyRating: 'A',
        features: {
            pool: 'private',
            parking: true,
            parkingSpaces: 2,
            elevator: false,
            garden: true,
            gated: true,
            terrace: true,
            airConditioning: true,
            heating: true,
            storage: true,
            furnished: false,
        },
        distances: {
            beach: 500,
            golf: true,
            schools: true,
            commercialCenter: true,
        },
        descriptions: {
            sv: 'Modern villa med panoramautsikt över Medelhavet. Stor terrass och infinity pool.',
            en: 'Modern villa with panoramic views of the Mediterranean. Large terrace and infinity pool.',
            es: 'Villa moderna con vistas panorámicas al Mediterráneo. Gran terraza y piscina infinita.',
        },
        images: [
            'https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2070&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=2071&auto=format&fit=crop',
        ],
        dateUpdated: '2024-01-15',
        dateListed: '2024-01-01',
    },
    {
        id: '2',
        ref: 'SP0893',
        slug: 'penthouse-nerja-sea-view',
        price: 595000,
        currency: 'EUR',
        type: 'Penthouse',
        title: 'Penthouse Las Lomas',
        isNewBuild: true,
        town: 'Nerja',
        province: 'Málaga',
        country: 'Spain',
        locationDetail: 'Las Lomas',
        coordinates: { lat: 36.7449, lng: -3.8779 },
        region: 'costa-del-sol',
        beds: 2,
        baths: 2,
        builtArea: 95,
        terraceArea: 45,
        energyRating: 'B',
        features: {
            pool: 'communal',
            parking: true,
            parkingSpaces: 1,
            elevator: true,
            garden: false,
            gated: true,
            terrace: true,
            airConditioning: true,
            heating: false,
            storage: false,
            furnished: true,
        },
        distances: {
            beach: 200,
            golf: true,
            schools: true,
        },
        descriptions: {
            sv: 'Nyproducerad takvåning med privat takterrass och jacuzzi.',
            en: 'Newly built penthouse with private rooftop terrace and jacuzzi.',
            es: 'Ático de nueva construcción con terraza privada en la azotea y jacuzzi.',
        },
        images: [
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop',
        ],
        dateUpdated: '2024-01-15',
        dateListed: '2024-01-10',
    },
    {
        id: '3',
        ref: 'SP0894',
        slug: 'townhouse-alicante-garden',
        price: 345000,
        currency: 'EUR',
        type: 'Townhouse',
        title: 'Casa Blanca Garden',
        isNewBuild: false,
        town: 'Alicante',
        province: 'Alicante',
        country: 'Spain',
        coordinates: { lat: 38.3452, lng: -0.4815 },
        region: 'costa-blanca',
        beds: 3,
        baths: 2,
        builtArea: 120,
        plotArea: 400,
        features: {
            pool: 'communal',
            parking: true,
            parkingSpaces: 1,
            elevator: false,
            garden: true,
            gated: false,
            terrace: true,
            airConditioning: true,
            heating: false,
            storage: false,
            furnished: false,
        },
        distances: {
            schools: true,
            commercialCenter: true,
        },
        descriptions: {
            sv: 'Charmigt radhus med lummig trädgård i lugnt område.',
            en: 'Charming townhouse with lush garden in quiet area.',
            es: 'Encantadora casa adosada con jardín frondoso en zona tranquila.',
        },
        images: [
            'https://images.unsplash.com/photo-1580587771525-78b9dba3b91d?q=80&w=1974&auto=format&fit=crop',
        ],
        dateUpdated: '2024-01-12',
        dateListed: '2023-12-01',
    },
    {
        id: '4',
        ref: 'SP0895',
        slug: 'apartment-torrevieja-beachfront',
        price: 285000,
        currency: 'EUR',
        type: 'Apartment',
        title: 'Torrevieja Beachfront',
        isNewBuild: false,
        town: 'Torrevieja',
        province: 'Alicante',
        country: 'Spain',
        locationDetail: 'Playa del Cura',
        coordinates: { lat: 37.9789, lng: -0.6822 },
        region: 'costa-blanca',
        beds: 3,
        baths: 2,
        builtArea: 110,
        features: {
            pool: 'none',
            parking: false,
            elevator: true,
            garden: false,
            gated: false,
            terrace: true,
            airConditioning: true,
            heating: false,
            storage: false,
            furnished: true,
        },
        distances: {
            beach: 50,
            commercialCenter: true,
        },
        descriptions: {
            sv: 'Ljus lägenhet precis vid stranden Playa del Cura.',
            en: 'Bright apartment right by Playa del Cura beach.',
            es: 'Apartamento luminoso junto a la playa del Cura.',
        },
        images: [
            'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=2070&auto=format&fit=crop',
        ],
        dateUpdated: '2024-01-10',
        dateListed: '2023-11-15',
    },
];

export const MOCK_AREAS: Area[] = [
    {
        slug: 'marbella',
        name: 'Marbella',
        region: 'costa-del-sol',
        province: 'Málaga',
        propertyCount: 450,
        priceRange: { min: 250000, max: 5000000 },
        avgPrice: 850000,
        image:
            'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=2070&auto=format&fit=crop',
        description:
            'Lyx, golf och stränder i världsklass. Solkustens pärla erbjuder en livsstil utöver det vanliga.',
    },
    {
        slug: 'alicante',
        name: 'Alicante & Costa Blanca',
        region: 'costa-blanca',
        province: 'Alicante',
        propertyCount: 630,
        priceRange: { min: 100000, max: 2000000 },
        avgPrice: 350000,
        image:
            'https://images.unsplash.com/photo-1577791465508-34eb10825310?q=80&w=1974&auto=format&fit=crop',
        description:
            'Milslånga vita stränder, saltlaguner och ett fantastiskt klimat året runt.',
    },
    {
        slug: 'nerja',
        name: 'Nerja',
        region: 'costa-del-sol',
        province: 'Málaga',
        propertyCount: 180,
        priceRange: { min: 200000, max: 1500000 },
        avgPrice: 450000,
        image:
            'https://images.unsplash.com/photo-1563789031959-4c02bcb41319?q=80&w=1974&auto=format&fit=crop',
        description:
            'Den genuina pärlan öster om Málaga med sina berömda grottor och Balcón de Europa.',
    },
];
